### ISSUE TITLE
MQTT commands structure

### ISSUE THREAD

**Issue by chrishutt** [steffenmllr/node-red-contrib-sonoff-tasmota#2]
To make this work with my version of tasmota (5.6.1c) I had to change the structure of the mqtt commands in sonoff.js to put config.id in front as follows, otherwise nothing works.

        const topicTeleLWT = `${config.id}/${config.telePrefix}/LWT`;

        const topicCmdPower = `${config.id}/${config.cmdPrefix}/power`;
        const topicCmdStatus = `${config.id}/${config.cmdPrefix}/status`;

        const topicStatsPower = `${config.id}/${config.statPrefix}/POWER`;
        const topicStatsStatus = `${config.id}/${config.statPrefix}/STATUS`;

**Comment by steffenmllr** [comment]
@chrishutt thanks for the heads up - I didn't update the firmware for a while (Running 4.1). If you have the time, a Pull Request would be most welcome :)

**Comment by cjaferre** [comment]
According to https://github.com/arendst/Sonoff-Tasmota/wiki/MQTT-Overview#tldr the correct and actual mqtt structure is "cmnd/mySonoffID/power"

I just installed tasmota on my sonoff device and comfirm this.

**Comment by steffenmllr** [comment]
fixed in 2.1.0
