### ISSUE TITLE
Your package is not listed in NodeRed.org

### ISSUE THREAD

**Issue by PKGeorgiev** [steffenmllr/node-red-contrib-sonoff-tasmota#7]
Hi,
For some reason node-red-contrib-sonoff-tasmota is not listed under "Flows" section in nodered.org.

**Comment by steffenmllr** [comment]
Hmm any idea how to list the package there? I thought naming it `node-red-contrib-*` was enough.

**Comment by PKGeorgiev** [comment]
I think you are missing "keywords" option in package.json. Here is the guide: https://nodered.org/docs/creating-nodes/packaging#packagejson

Adding it will make installation even easier from within NodeRed > MainMenu > Manage Palette > Install

**Comment by steffenmllr** [comment]
Thanks for the hint. I've added the keyword and published as 2.1.1

**Comment by PKGeorgiev** [comment]
Offtopic: how did you come up with the idea of using the node "mqtt-broker" (RED.nodes.getNode(config.broker))? Is there a guide? Just curious :)

**Comment by steffenmllr** [comment]
I browsed a couple of node red repos and found the idea here: https://github.com/marvinroger/node-red-contrib-homie/blob/master/nodes/deviceconfig/deviceconfig.html

*edit: wasn't the right repo. I found it somewhere on github :)*
